import ConvertitoreMigliaKilometri from "@/components/converters/ConvertitoreMigliaKilometri";

export const metadata = {
  title: "Converti",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <ConvertitoreMigliaKilometri />
    </>
  )
}
